sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: xiaoyuan
  alioss:
    endpoint: https://oss-cn-beijing.aliyuncs.com
    bucket-name: sky-itcast00-0
  redis:
    host: localhost
    port: 6379
    database: 0
  wechat:
    appid: eb6ead47bc9bc59417d4ad52f9d42796
    secret: wxe0e9f009058453c6
